blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/timmeromberg/whisper-dic/discussions/categories/q-a
    about: Ask questions and get help from the community.
  - name: Share an Idea
    url: https://github.com/timmeromberg/whisper-dic/discussions/categories/ideas
    about: Suggest ideas and discuss features before opening an issue.
