blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/timmeromberg/whisper-dic/issues
    about: For questions, open a regular issue with the "question" label.
